SELECT STP_NAME, BNF_CODE
FROM snow.FACT_TABLE
JOIN snow.PRESCRIPTION ON FACT_TABLE.prescription_key = PRESCRIPTION.PRESCRIPTION_KEY
JOIN snow.LOCATION ON FACT_TABLE.LOCATION_KEY = LOCATION.LOCATION_KEY 
ORDER BY STP_NAME


SELECT TIME.MONTH as "Month", SUM(NIC) as "NIC", SUM(ACTUAL_COST) as "total_sales"
FROM snow.FACT_TABLE
JOIN snow.TIME ON FACT_TABLE.TIME_KEY = TIME.TIME_KEY
JOIN snow.PRESCRIPTION ON PRESCRIPTION.PRESCRIPTION_KEY = FACT_TABLE.PRESCRIPTION_KEY
WHERE TIME.YEAR = 2021
GROUP BY (TIME.MONTH)
ORDER BY (TIME.MONTH)


SELECT STP_NAME, PCO_NAME FROM snow.LOCATION